### ISSUE TITLE
Re-filter drug sensitivity data to determine numbers

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/BeatAMLproteomics#12]
In the pilot data we filtered drugs to identify those that were sensitive (e.g. AUC <100) to the drug in at least 10% of all patients. We need a function in this package that does the same as [this previous code](https://github.com/PNNL-CompBio/beatAMLpilotProteomics/blob/de119a8a801e9b9251c5ef90325dbc575dc9aa88/beatAMLdata.R#L142).

**Comment by CamiloPosso** [comment]
Should be solved by https://github.com/PNNL-CompBio/BeatAMLproteomics/pull/14
