### ISSUE TITLE
Re-create Figure 1 plots with new data

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/BeatAMLproteomics#13]
Copy fig1 R Markdown from the [pilot proteomics repository](https://github.com/PNNL-CompBio/beatAMLpilotProteomics/blob/main/pilotManuscript/fig1_dataSummary.Rmd). Keep in mind that I am computing very large correlations in dot plots, so they might be slow. My primary question is how many drugs and samples we have.

**Comment by CamiloPosso** [comment]
Should be solved by https://github.com/PNNL-CompBio/BeatAMLproteomics/pull/16
