### ISSUE TITLE
Fig 2- Compute differential expression of various genetic signatures

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/BeatAMLproteomics#20]
using the skeleton code in the [pilot paper repository](https://github.com/PNNL-CompBio/beatAMLpilotProteomics/blob/main/pilotManuscript/fig9_mutationalSigs.Rmd) we can identify those proteins, transcripts, and phosphosites that are significantly changing in FLT3, NPM1, and other mutated patients.

How many proteins/phosphosites/transcripts are differnetially expressed?
What pathways/kinases are enriched via GO/KSEA?
how do these translate to networks (using hierarchical hotnet)

**Comment by CamiloPosso** [comment]
heatmap of all mutation data from genes with mutation on at least 10 patients.

**Comment by sgosline** [comment]
Summarize this in a table: 
1- how many transcripts, proteins, and phosphosites that are differentially expressed for each gene that is mutated.
2- how many go terms are enriched for each mutation and data combination
3- example heatmaps to describe your work.

**Comment by sgosline** [comment]
First summarize #1 from above as a bar chart to estimate the relative changes that occur across different mutations. 

For steps 2-3, focus on:
1- WES mutations from IDH1, IDH2, TP53, NRAS, KRAS
2- WES mutations from union of IDH1 and IDH2 and union of KRAS/NRAS
3- FLT3 ITD
4- NPM clinical calls

**Comment by CamiloPosso** [comment]
#50 includes the latest updates to this issue. The ORA and GSEA plots are here for the special selected mutations: https://www.synapse.org/#!Synapse:syn26529351
