### ISSUE TITLE
Create  data summary MD of the data once loaded

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/BeatAMLproteomics#7]
Once we have the data loaded we can then create some figures that re-use the old code from https://github.com/PNNL-CompBio/beatAMLpilotProteomics/blob/main/pilotManuscript/fig1_dataSummary.Rmd

Copy this MD into this repository (a 'figures' folder maybe) and then work on getting it to render with the data loaded from #6

**Comment by sgosline** [comment]
also solved by @CamiloPosso  in PR #9

**Comment by CamiloPosso** [comment]
Extra comment: Don't forget to make table including the "sensitivity" and number missing information for each drug.
